// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  symbol_sdk: [
    {
      type: "category",
      label: "Symbol SDK",
      items: [
        {
          type: "autogenerated",
          dirName: "symbol_sdk",
        },
      ],
    }
  ],
  node: [
    {
      type: "category",
      label: "Node",
      items: [
        {
          type: "autogenerated",
          dirName: "node",
        },
      ],
    }
  ]
};

module.exports = sidebars;
